# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redish.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='redish.proto',
  package='redish',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0credish.proto\x12\x06redish\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bSingleValue\x12\r\n\x05value\x18\x01 \x01(\t\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x04\n\x02OK2\\\n\x06Redish\x12)\n\x03get\x12\x0b.redish.Key\x1a\x13.redish.SingleValue\"\x00\x12\'\n\x03set\x12\x12.redish.SetRequest\x1a\n.redish.OK\"\x00\x62\x06proto3')
)




_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='redish.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='redish.Key.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=42,
)


_SINGLEVALUE = _descriptor.Descriptor(
  name='SingleValue',
  full_name='redish.SingleValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='redish.SingleValue.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=72,
)


_SETREQUEST = _descriptor.Descriptor(
  name='SetRequest',
  full_name='redish.SetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='redish.SetRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='redish.SetRequest.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=114,
)


_OK = _descriptor.Descriptor(
  name='OK',
  full_name='redish.OK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['SingleValue'] = _SINGLEVALUE
DESCRIPTOR.message_types_by_name['SetRequest'] = _SETREQUEST
DESCRIPTOR.message_types_by_name['OK'] = _OK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'redish_pb2'
  # @@protoc_insertion_point(class_scope:redish.Key)
  })
_sym_db.RegisterMessage(Key)

SingleValue = _reflection.GeneratedProtocolMessageType('SingleValue', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEVALUE,
  '__module__' : 'redish_pb2'
  # @@protoc_insertion_point(class_scope:redish.SingleValue)
  })
_sym_db.RegisterMessage(SingleValue)

SetRequest = _reflection.GeneratedProtocolMessageType('SetRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETREQUEST,
  '__module__' : 'redish_pb2'
  # @@protoc_insertion_point(class_scope:redish.SetRequest)
  })
_sym_db.RegisterMessage(SetRequest)

OK = _reflection.GeneratedProtocolMessageType('OK', (_message.Message,), {
  'DESCRIPTOR' : _OK,
  '__module__' : 'redish_pb2'
  # @@protoc_insertion_point(class_scope:redish.OK)
  })
_sym_db.RegisterMessage(OK)



_REDISH = _descriptor.ServiceDescriptor(
  name='Redish',
  full_name='redish.Redish',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=122,
  serialized_end=214,
  methods=[
  _descriptor.MethodDescriptor(
    name='get',
    full_name='redish.Redish.get',
    index=0,
    containing_service=None,
    input_type=_KEY,
    output_type=_SINGLEVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='set',
    full_name='redish.Redish.set',
    index=1,
    containing_service=None,
    input_type=_SETREQUEST,
    output_type=_OK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REDISH)

DESCRIPTOR.services_by_name['Redish'] = _REDISH

# @@protoc_insertion_point(module_scope)
